apiVersion: v1
kind: Namespace
metadata:
  name: webapp1

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp1
  namespace: webapp1
spec:
  ingressClassName: nginx
  rules:
  - host: webapp1.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: webapp1
              port:
                number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webapp1
  namespace: webapp1
spec:
  type: ClusterIP
  selector:
    app: webapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  namespace: webapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: nginx
        ports:
        - containerPort: 80
        resources:
