apiVersion: v1
kind: Namespace
metadata:
  name: webapp2

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp2
  namespace: webapp2
spec:
  ingressClassName: nginx
  rules:
  - host: webapp2.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: webapp2
              port:
                number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webapp2
  namespace: webapp2
spec:
  type: ClusterIP
  selector:
    app: webapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
  namespace: webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - name: webapp2
        image: nginx
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: webapp2
        - secretRef:
            name: webapp2
        resources:

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp2
  namespace: webapp2
data:
  Foo: Bar

---

apiVersion: v1
kind: Secret
metadata:
  name: webapp2
  namespace: webapp2
data:
  SecretFoo: U2VjcmV0QmFy
